### Numpy
1. Package/Library in Python to perform mathematical operations on Array
2. Work on Multidimentional Arrays (1d,2d,3d)
3. Array - Group of Homogenous Data
4. Array can not store multiple type of data but list does


In [1]:
a1 = [1,2,3,4,5]
a2 = [10,11,12,13,14]
a3 = a1 + a2    ## [11,13,15,17,19] without using np it concatinated
a3

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([10,11,12,13,14])
type(a1)

numpy.ndarray

In [4]:
a3 = a1 + a2
print(a3)

[11 13 15 17 19]


In [5]:
a1 = np.array([1,3,4,5,3,4,5,3,5,10])   ## 1d array
a2 = np.array([[1,3,4,5,3,4,5,3,5,10]])   ## 2d array
a3 = np.array([[1,3,4,5,3,4,5,3,5,10],[1,3,4,5,3,4,5,3,5,10],[1,3,4,5,3,4,5,3,5,10]])  ## 2d array
a4 = np.array([[[1,3,4,5,3,4,5,3,5,10],[1,3,4,5,3,4,5,3,5,10],[1,3,4,5,3,4,5,3,5,10]]])  ## 3d array

In [6]:
# To check the array 
print(a1.ndim)  
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)

1
2
2
3


In [7]:
print(len(a1))
print(len(a2))
print(len(a3))
print(len(a4))

10
1
3
1


In [8]:
a4

array([[[ 1,  3,  4,  5,  3,  4,  5,  3,  5, 10],
        [ 1,  3,  4,  5,  3,  4,  5,  3,  5, 10],
        [ 1,  3,  4,  5,  3,  4,  5,  3,  5, 10]]])

In [9]:
### 2d array - len - it will give no. of (2-1)d array
### 3d array - len - it will give no. of (3-1)d array

In [10]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)

(10,)
(1, 10)
(3, 10)
(1, 3, 10)


In [11]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)

int64
int64
int64
int64


In [12]:
a4.shape[1]

3

In [13]:
#### Random Data

In [14]:
np.random.randint(100)   ## single random number 0 to 99

90

In [15]:
np.random.seed(100)   ## any value b/w 0 to 2**32 -1 (4294967295)
print(np.random.randint(100))

8


In [16]:
np.random.randint(100,1000)   ## 100-999

892

In [17]:
np.random.randint(100,1000,100)

array([935, 971, 955, 179, 450, 966, 153, 678, 838, 626, 902, 852, 380,
       755, 328, 975, 416, 670, 607, 749, 193, 186, 486, 767, 976, 515,
       997, 241, 857, 823, 712, 104, 703, 935, 235, 149, 531, 805, 417,
       882, 795, 863, 436, 102, 989, 717, 578, 503, 163, 281, 383, 924,
       338, 469, 403, 779, 977, 906, 272, 374, 292, 537, 814, 373, 684,
       625, 718, 130, 117, 153, 168, 588, 447, 575, 793, 946, 100, 113,
       285, 560, 462, 231, 682, 743, 312, 819, 494, 315, 602, 595, 743,
       973, 276, 280, 911, 136, 873, 939, 138, 314])

In [18]:
np.random.randint(100,1000,(5,5))

array([[194, 838, 270, 952, 195],
       [726, 849, 731, 176, 901],
       [414, 202, 506, 356, 862],
       [795, 326, 921, 296, 546],
       [918, 552, 519, 507, 865]])

In [19]:
np.random.randint(100,1000,(3,5,5))

array([[[621, 596, 889, 509, 538],
        [362, 777, 970, 222, 728],
        [286, 395, 719, 834, 919],
        [386, 989, 678, 343, 539],
        [373, 913, 585, 189, 529]],

       [[903, 116, 624, 954, 566],
        [721, 167, 320, 323, 888],
        [238, 876, 573, 812, 514],
        [758, 449, 987, 704, 656],
        [345, 157, 483, 868, 685]],

       [[844, 794, 934, 756, 489],
        [535, 446, 134, 551, 962],
        [794, 177, 312, 485, 114],
        [983, 389, 248, 268, 636],
        [577, 542, 896, 822, 747]]])

In [20]:
np.random.seed(1)
np.random.uniform(100,1000,(5,5)) ## uniform for floating number

array([[475.31980423, 748.2920441 , 100.10293734, 372.09931537,
        232.08030174],
       [183.10473529, 267.63419024, 411.00465434, 457.09072681,
        584.9350606 ],
       [477.27506296, 716.69755036, 284.00702476, 890.30569275,
        124.64883388],
       [703.42075916, 475.57432213, 602.8208456 , 226.34824474,
        278.29134018],
       [820.67011181, 971.43541815, 382.08176034, 723.0903541 ,
        888.75023707]])

In [21]:
a = np.random.uniform(100,1000,(5,5))
np.round(a,2)  #round for extracting number

array([[905.15, 176.54, 135.15, 252.85, 890.33],
       [188.51, 479.  , 962.1 , 579.85, 722.69],
       [383.96, 717.85, 851.16, 116.46, 775.13],
       [989.97, 773.35, 352.4 , 810.35, 192.9 ],
       [503.1 , 917.74, 364.25, 359.  , 217.03]])

In [22]:
a = np.random.uniform(100,1000,(5,5))
np.ceil(a) #ceil for uptill dot

array([[118., 711., 291., 339., 543.],
       [149., 617., 233., 631., 730.],
       [193., 473., 725., 473., 145.],
       [583., 698., 564., 951., 628.],
       [914., 224., 226., 827., 458.]])

In [23]:
#### Array Slicing

In [24]:
np.random.seed(1)
arr = np.random.randint(1,20,(8,6))
arr

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [25]:
arr[:,:]   ## rows,columns

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [26]:
arr[2:6,2:5]

array([[ 7, 19,  6],
       [15, 19,  5],
       [14, 10, 10],
       [18,  9, 14]])

In [27]:
arr[3,3]

19

In [28]:
### Array Functions

In [29]:
arr

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [30]:
print(arr.sum())
print(arr.sum(axis=0))  ## column wise
print(arr.sum(axis=1))  # row wise

509
[ 67  69  94  99  67 113]
[62 55 73 72 61 60 57 69]


In [31]:
print(arr.mean())
print(arr.mean(axis=0))  ## column wise
print(arr.mean(axis=1))  # row wise

10.604166666666666
[ 8.375  8.625 11.75  12.375  8.375 14.125]
[10.33333333  9.16666667 12.16666667 12.         10.16666667 10.
  9.5        11.5       ]


In [32]:
print(arr.min())
print(arr.min(axis=0))  ## column wise
print(arr.min(axis=1))  # row wise

1
[2 1 1 4 2 8]
[6 1 6 5 1 1 4 4]


In [33]:
print(arr.max())
print(arr.max(axis=0))  ## column wise
print(arr.max(axis=1))  # row wise

19
[18 16 18 19 14 19]
[13 17 19 19 18 18 18 18]


In [34]:
print(arr.argmin())  ## position of minimum number
print(arr.argmin(axis=0))  ## column wise
print(arr.argmin(axis=1))  # row wise

8
[5 4 1 6 1 4]
[0 2 4 4 1 1 3 0]


In [35]:
arr

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [36]:
print(arr.argmax())   ## position of maximum number
print(arr.argmax(axis=0))  ## column wise
print(arr.argmax(axis=1))  # row wise

15
[4 1 5 2 5 2]
[2 3 3 3 0 2 5 2]


In [37]:
arr

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [38]:
### Change shape of dimension of array
arr.shape

(8, 6)

In [39]:
arr.size

48

In [40]:
arr_1 = arr.reshape(48)
arr_2 = arr.reshape(4,12)   ## (6,8),(4,12),(12,4),(24,2),(2,24),(48,1),(1,48)
arr_3 = arr.reshape(3,2,8)

In [41]:
arr

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [42]:
arr.astype('float32')

array([[ 6., 12., 13.,  9., 10., 12.],
       [ 6., 16.,  1., 17.,  2., 13.],
       [ 8., 14.,  7., 19.,  6., 19.],
       [12., 11., 15., 19.,  5., 10.],
       [18.,  1., 14., 10., 10.,  8.],
       [ 2.,  1., 18.,  9., 14., 16.],
       [11.,  9.,  8.,  4.,  7., 18.],
       [ 4.,  5., 18., 12., 13., 17.]], dtype=float32)

In [43]:
arr.astype('int32')

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]], dtype=int32)

In [44]:
arr.astype('str')

array([['6', '12', '13', '9', '10', '12'],
       ['6', '16', '1', '17', '2', '13'],
       ['8', '14', '7', '19', '6', '19'],
       ['12', '11', '15', '19', '5', '10'],
       ['18', '1', '14', '10', '10', '8'],
       ['2', '1', '18', '9', '14', '16'],
       ['11', '9', '8', '4', '7', '18'],
       ['4', '5', '18', '12', '13', '17']], dtype='<U21')

In [45]:
np.sum(arr)

509

In [46]:
### Standard Matrices
np.zeros((5,5),np.uint8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [47]:
np.ones((5,5),np.uint8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [48]:
np.identity(5,np.uint8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [49]:
### Random String
import random
mystr = "1234567890-=qwertyuiopasdfghjkl'zxccvbn,.!@#$%^&*()_+"
length = 10
random_string = "".join(random.sample(mystr,length))
random_string

'4rj98q%b=d'